### ISSUE TITLE
How would you go about adding a button that clears the AR scene?

### ISSUE THREAD

**Issue by tavst3r** [backslash-f/realitykit-swiftui#1]
Hello! 

The project is great! I am trying to learn Swift and AR developing and I was wondering how would you go about adding a button that removes all the 3d objects form the AR scene. Could you help me with this?

Thank you!

**Comment by backslash-f** [comment]
Hi!

Yeah, this was a good exercise.

ChatGPT helped me on this one 😁: [chatgpt.txt](https://github.com/backslash-f/realitykit-swiftui/files/11211188/chatgpt.txt)

So:
1. Set a name for the entities to be added to the scene: https://github.com/backslash-f/realitykit-swiftui/commit/ff1a7f5bc10b50871180807df54ae9ebdfd4c711
2. Add the removal capability to the `ARViewRepresentable`: https://github.com/backslash-f/realitykit-swiftui/commit/f2c75ca8e7d6b9c7719b3140ea6e6b5a31664206
3. Add the delete button + state: https://github.com/backslash-f/realitykit-swiftui/commit/81c5f93851844e126accc3acd6e4dcd68a403013

Profit:

https://user-images.githubusercontent.com/664951/231454131-432c17bf-67f4-4093-a12b-d7e1a1747f84.mp4

**Comment by tavst3r** [comment]
Thank you!
